-- ==============================================================================
-- Numen Waitlist - Supabase PostgreSQL Schema & Security Policy Fix
-- ==============================================================================
-- Instructions:
-- 1. Go to your Supabase project (numen-waitlist) at https://supabase.com/dashboard
-- 2. Click "SQL Editor" on the left menu
-- 3. Paste all the code below and click "Run" (green button)
-- ==============================================================================

-- 1. Create the waitlist_signups table if it doesn't already exist
CREATE TABLE IF NOT EXISTS public.waitlist_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    referrer TEXT,
    user_agent TEXT
);

-- 2. Create index on email for fast lookups
CREATE INDEX IF NOT EXISTS waitlist_signups_email_idx ON public.waitlist_signups (email);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.waitlist_signups ENABLE ROW LEVEL SECURITY;

-- 4. Clean up any existing policies
DROP POLICY IF EXISTS "Allow public insert to waitlist" ON public.waitlist_signups;
DROP POLICY IF EXISTS "Enable insert for anon users" ON public.waitlist_signups;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.waitlist_signups;
DROP POLICY IF EXISTS "Enable insert for anon" ON public.waitlist_signups;

-- 5. Allow anonymous visitors to insert into the waitlist
CREATE POLICY "Enable insert for anon"
ON public.waitlist_signups
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 6. Create secure function to get live count
CREATE OR REPLACE FUNCTION public.get_waitlist_count()
RETURNS INTEGER
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT count(*)::integer FROM public.waitlist_signups;
$$;

GRANT EXECUTE ON FUNCTION public.get_waitlist_count() TO anon, authenticated;
