-- ==============================================================================
-- Numen Waitlist - Supabase PostgreSQL Schema
-- ==============================================================================
-- To set up this database:
-- 1. Create a free project at https://supabase.com
-- 2. Open the SQL Editor from the left sidebar
-- 3. Paste this script and click "Run"
-- ==============================================================================

-- 1. Create the waitlist_signups table
CREATE TABLE IF NOT EXISTS public.waitlist_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    referrer TEXT,
    user_agent TEXT
);

-- 2. Create index on email for quick lookups
CREATE INDEX IF NOT EXISTS waitlist_signups_email_idx ON public.waitlist_signups (email);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.waitlist_signups ENABLE ROW LEVEL SECURITY;

-- 4. Allow anonymous visitors (public) to insert their email into the waitlist
CREATE POLICY "Allow public insert to waitlist"
ON public.waitlist_signups
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 5. Create a secure function to retrieve the total count without exposing emails
CREATE OR REPLACE FUNCTION public.get_waitlist_count()
RETURNS INTEGER
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT count(*)::integer FROM public.waitlist_signups;
$$;

-- 6. Grant execute permission on the count function to anon & authenticated users
GRANT EXECUTE ON FUNCTION public.get_waitlist_count() TO anon, authenticated;
